### ISSUE TITLE
Problem about data of /laserscan "wobble"

### ISSUE THREAD

**Issue by Octalivia** [Hypha-ROS/hypharos_minicar#11]
when my racecar make a turn at a high speed (3m/s, a slight turn), the laser scan "wobble" , it also happens in the hypharos simulation platforn. How to solve this problem?

**Comment by wqb2249654300** [comment]
Hello, I want to ask why the speed can not be greater than 1m / s when I simulate? There is no response to modifying the parameter max_speed.

**Comment by wqb2249654300** [comment]
Hello, I want to ask why the speed can not be greater than 1m / s when I simulate? There is no response to modifying the parameter max_speed.

**Comment by Octalivia** [comment]
> Hello, I want to ask why the speed can not be greater than 1m / s when I simulate? There is no response to modifying the parameter max_speed.

you need to add "velocity bounds" for your robot model. Such as the following.
`define carlike_robot position
(
  pose [ 0.0 0.0 0.0 0.0 ]
  # odom_error [0 0 0 0 0 0]
   odom_error [0.03 0.03 999999 999999 999999 0.02]
  velocity_bounds [-5 5 -5 5 -5 5 -90 90]
  size [ 0.40 0.30 0.40 ] # this models the footprint (rectangular), but shifted such that the bottom-left corner is in [0,0]. The center of rotation now here at [0.3, 0.125, 0.2]
  # correct center of rotation:
  origin [ 0.25 0.1 0.0 0.0]
  gui_nose 1
  color "red"

  # kinematics
  drive "car"
  wheelbase 0.4 # distance between both axles
  
  # spawn sensors
  laser(pose [ 0.3 0.0 0.1 0.0 ])
)`

**Comment by Octalivia** [comment]
> Hello, I want to ask why the speed can not be greater than 1m / s when I simulate? There is no response to modifying the parameter max_speed.

you need to add "velocity bounds" for your robot model in the .inc file.  Such as the following.
velocity_bounds [-5 5 -5 5 -5 5 -90 90]

**Comment by haochihlin** [comment]
Hi @Octalivia ,

About the "wobble" effect of laser, I guess the cause is the drift of wheel.
In order to get better localization performance (via amcl), we need good odometry estimation.
The current odom estimate on minicar only based on wheel encoder. So there are two potential issues: (1) when steering, one wheel (or both wheel) is/are slipping a bit. (2) When acceleration is too high, the wheel would slip for a moment. To tackle these slipping issue, you can either fuse the wheel odom with onboard imu by EKF or fuse with laser odometry (e.g. rf2o).
